In [ ]:
count = 0
while count < 5:
    print(count)
    count += 1


0
1
2
3
4


In [ ]:
x = 10
y = 20

print(x == y)  # False (10 is not equal to 20)
print(x != y)  # True  (10 is not equal to 20)
print(x < y)   # True  (10 is less than 20)
print(x > y)   # False (10 is not greater than 20)
print(x <= 10) # True  (10 is less than or equal to 10)
print(x >= 5)  # True  (10 is greater than or equal to 5)



False
True
True
False
True
True


In [ ]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

def main():
    num = int(input("Enter a number: "))
    print(f"The factorial of {num} is {factorial(num)}")

if __name__ == "__main__":
    main()

Enter a number: 15
The factorial of 15 is 1307674368000


In [ ]:


def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

num = int(input("Enter a number: "))
print(f"The factorial of {num} is {factorial(num)}")




Enter a number: 15
The factorial of 15 is 1307674368000


In [ ]:
text = "Hello, Python!"

# Basic Slicing
print(text[0:5])  # 'Hello' (from index 0 to 4)
print(text[:5])   # 'Hello' (same as above, start defaults to 0)
print(text[7:])   # 'Python!' (from index 7 to the end)

# Negative Indexing
print(text[-7:])  # 'Python!' (last 7 characters)
print(text[:-7])  # 'Hello,' (everything except the last 7 characters)

# Step in Slicing
print(text[::2])  # 'Hlo yhn' (every 2nd character)
print(text[::-1]) # '!nohtyP ,olleH' (reversed string)


Hello
Hello
Python!
Python!
Hello, 
Hlo yhn
!nohtyP ,olleH


In [ ]:
lst = [0, 1, 2, 3, 4, 5]

# Basic Slicing
print(lst[1:4])   # [1, 2, 3] (from index 1 to 3)
print(lst[:3])    # [0, 1, 2] (first three elements)
print(lst[3:])    # [3, 4, 5] (elements from index 3 to the end)

# Negative Indexing
print(lst[-3:])   # [3, 4, 5] (last 3 elements)
print(lst[:-3])   # [0, 1, 2] (everything except the last 3 elements)

# Step in Slicing
print(lst[::2])   # [0, 2, 4] (every 2nd element)
print(lst[::-1])  # [5, 4, 3, 2, 1, 0] (reversed list)


[1, 2, 3]
[0, 1, 2]
[3, 4, 5]
[3, 4, 5]
[0, 1, 2]
[0, 2, 4]
[5, 4, 3, 2, 1, 0]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

# Basic Slicing
print(arr[1:4])   # [20 30 40] (from index 1 to 3)
print(arr[:3])    # [10 20 30] (first 3 elements)
print(arr[3:])    # [40 50 60] (from index 3 to the end)

# Negative Indexing
print(arr[-3:])   # [40 50 60] (last 3 elements)
print(arr[:-3])   # [10 20 30] (everything except the last 3 elements)

# Step in Slicing
print(arr[::2])   # [10 30 50] (every 2nd element)
print(arr[::-1])  # [60 50 40 30 20 10] (reversed array)


[20 30 40]
[10 20 30]
[40 50 60]
[40 50 60]
[10 20 30]
[10 30 50]
[60 50 40 30 20 10]


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Row Slicing
print(arr_2d[:2, :])  # First 2 rows
# [[1 2 3]
#  [4 5 6]]

# Column Slicing
print(arr_2d[:, 1:])  # All rows, columns 1 to the end
# [[2 3]
#  [5 6]
#  [8 9]]

# Specific Rows and Columns
print(arr_2d[1:, 1:])  # Rows 1 to the end, columns 1 to the end
# [[5 6]
#  [8 9]]


[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[5 6]
 [8 9]]


In [ ]:
tup = (10, 20, 30, 40, 50)

# Basic Slicing
print(tup[1:4])   # (20, 30, 40)
print(tup[:3])    # (10, 20, 30)

# Step in Slicing
print(tup[::2])   # (10, 30, 50) (every 2nd element)
print(tup[::-1])  # (50, 40, 30, 20, 10) (reversed tuple)


(20, 30, 40)
(10, 20, 30)
(10, 30, 50)
(50, 40, 30, 20, 10)


In [ ]:
my_list = [10, 20, 30, 40]
print(my_list[0])   # 10 (first element)
print(my_list[-1])  # 40 (last element)


my_list.append(50)  # Add 50 to the end
print(my_list)      # [10, 20, 30, 40, 50]

my_list.insert(2, 25)  # Insert 25 at index 2
print(my_list)         # [10, 20, 25, 30, 40, 50]


10
40
[10, 20, 30, 40, 50]
[10, 20, 25, 30, 40, 50]


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
mixed_tuple = (1, "Python", 3.14)
print(my_tuple)      # (1, 2, 3, 4, 5)
print(mixed_tuple)   # (1, 'Python', 3.14)


(1, 2, 3, 4, 5)
(1, 'Python', 3.14)


In [ ]:
a, b, c = (1, 2, 3)
print(a, b, c)  # 1 2 3


1 2 3


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple.index(4))

3


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())      # 15
print(arr.mean())     # 3.0
print(arr.max())      # 5
print(arr.min())      # 1
print(arr.std())      # Standard deviation


15
3.0
5
1
1.4142135623730951


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.arange(10).reshape(2, 5)
print(np.hsplit(arr, 5))  # Split into 5 vertical subarrays


[array([[0],
       [5]]), array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]])]


In [ ]:
import pandas as pd
data = [['Alice', 25, 'New York'],
        ['Bob', 30, 'Los Angeles'],
        ['Charlie', 35, 'Chicago']]
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])

print(df)


      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [ ]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

result = pd.concat([df1, df2])  # Concatenate along rows
print(result)


   A  B
0  1  3
1  2  4
0  5  7
1  6  8


In [ ]:
left = pd.DataFrame({'ID': [1, 2], 'Name': ['Alice', 'Bob']})
right = pd.DataFrame({'ID': [1, 2], 'Salary': [50000, 60000]})

merged = pd.merge(left, right, on='ID')  # Merge on 'ID'
print(merged)


   ID   Name  Salary
0   1  Alice   50000
1   2    Bob   60000


In [ ]:
class Vehicle:
    def __init__(self, brand, model, year):
        self.brand = brand
        self.model = model
        self.year = year

    def start_engine(self):
        return f"{self.brand} {self.model}'s engine is starting..."

    def __str__(self):
        return f"{self.year} {self.brand} {self.model}"

class Car(Vehicle):
    def __init__(self, brand, model, year, doors):
        super().__init__(brand, model, year)
        self.doors = doors

    def start_engine(self):
        return f"{self.brand} {self.model} (Car) roars to life with a smooth start!"

class Motorcycle(Vehicle):
    def __init__(self, brand, model, year, type_of_bike):
        super().__init__(brand, model, year)
        self.type_of_bike = type_of_bike

    def start_engine(self):
        return f"{self.brand} {self.model} (Motorcycle) revs up with a powerful roar!"

# Example Usage
car = Car("Toyota", "Fortuner", 2022, 4)
bike = Motorcycle("Yamaha", "R3", 2023, "Sport")

print(car.start_engine())
print(bike.start_engine())


Toyota Fortuner (Car) roars to life with a smooth start!
Yamaha R3 (Motorcycle) revs up with a powerful roar!


In [ ]:
class Book:
    def __init__(self, title, author, pages):
        self.title = title
        self.author = author
        self.pages = pages

    def __str__(self):
        return f"{self.title} by {self.author}"

    def __repr__(self):
        return f"Book(title='{self.title}', author='{self.author}', pages={self.pages})"

    def __len__(self):
        return self.pages

    def __eq__(self, other):
        if not isinstance(other, Book):
            return NotImplemented
        return (self.title == other.title) and (self.author == other.author)

    def __lt__(self, other):
        if not isinstance(other, Book):
            return NotImplemented
        return self.pages < other.pages


b1 = Book("Harry potter and the philosopher stone", "JK Rowling", 150)
b2 = Book("Harry potter and the philosopher stone", "JK Rowling", 200)
print(str(b1))
print(repr(b1))
print(len(b1))
print(b1 == b2)
print(b1 < b2)



Harry potter and the philosopher stone by JK Rowling
Book(title='Harry potter and the philosopher stone', author='JK Rowling', pages=150)
150
True
True


In [ ]:
numbers =[10,20,30,40,50]
numbers.append(60)
numbers.remove(30)
first_element =numbers[0]
print("Updated List:", numbers)
print("First Element:", first_element)

Updated List: [10, 20, 40, 50, 60]
First Element: 10


In [ ]:
try:
    num = int(input("Enter a number: "))
    result = 10 / num
except ZeroDivisionError:
    print("Error: Division by zero!")
except ValueError:
    print("Error: Invalid input! Please enter a number.")


Enter a number: 0
Error: Division by zero!


In [ ]:
class BankAccount:
    def __init__(self, balance):
        self.balance = balance

    def withdraw(self, amount):
        try:
            if amount > self.balance:
                raise ValueError("Insufficient funds! Withdrawal amount exceeds balance.")
            self.balance -= amount
            return f"Withdrawal successful! Remaining balance: {self.balance}"
        except ValueError as e:
            return f"Error: {e}"

account = BankAccount(500)

print(account.withdraw(300))
print(account.withdraw(300))



Withdrawal successful! Remaining balance: 200
Error: Insufficient funds! Withdrawal amount exceeds balance.


In [ ]:
class BankAccount:
    def __init__(self, balance):
        self.balance = balance

    def withdraw(self, amount):
        try:
            if amount < 0:
                raise ValueError(" enter only a positive number.")
            if amount > self.balance:
                raise ValueError("Insufficient funds! Withdrawal amount exceeds balance.")
            else:
              self.balance -= amount
              return f"Withdrawal successful! Remaining balance: {self.balance}"
        except ValueError as e:
          return f"Error: {e}"

account = BankAccount(500)
print(account.withdraw(1000))
print(account.withdraw(-50))
print(account.withdraw(200))



Error: Insufficient funds! Withdrawal amount exceeds balance.
Error:  enter only a positive number.
Withdrawal successful! Remaining balance: 300


In [ ]:
try:
    num = int(input("Enter a number: "))
    result = 10 / num
except ZeroDivisionError:
    print("Error: Division by zero!")
except ValueError:
    print("Error: Invalid input! Please enter a number.")

Enter a number: 0
Error: Division by zero!


**Module4**


In [ ]:
with open("example4.txt", "w") as file:
  file.write("Hello,World!")

In [ ]:
with open("example5.txt","w") as file:
    file.write("This is a new line of text.\n")
    file.write("And another line.")

In [ ]:
with open("example5.txt","r") as file:
    content = file.read()
    print(content)

This is a new line of text.
And another line.


In [6]:
with open("example5.txt","w") as file:
   file.write("This is a new line of text.\n")
   file.write("Add another line")

In [7]:
with open("example5.txt","r") as file:
    content = file.read()
    print(content)

This is a new line of text.
Add another line


In [8]:
with open("example5.txt","r") as file:
  content = file.read(5)
  print(content)

This 


In [ ]:
with open("example5.txt","r") as file:
  content = file.read(15)
  print(content)

This is a new l


In [ ]:
with open("example5.txt","r") as file:
  lines = file.readlines()
  print(lines)

['This is a new line of text.\n', 'Add another line']


In [ ]:
with open("example5.txt","a") as file:
    file.write("\nAppending a new line.")

In [ ]:
with open("example5.txt","r") as file:
  content = file.read()
  print(content)

This is a new line of text.
Add another line
Appending a new line.


In [ ]:
try:
  with open('example5.txt','x') as file:
     file.write("This is a new line.")
except FileExistsError:
     print("File Already Exists.")

File Already Exists.


In [ ]:
with open('image.jpg','rb') as file:
  binary_data = file.read()
  print( binary_data)

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00\x84\x00\t\x06\x07\x08\x07\x06\t\x08\x07\x08\n\n\t\x0b\r\x16\x0f\r\x0c\x0c\r\x1b\x14\x15\x10\x16 \x1d"" \x1d\x1f\x1f$(4,$&1\'\x1f\x1f-=-157:::#+?D?8C49:7\x01\n\n\n\r\x0c\r\x1a\x0f\x0f\x1a7%\x1f%77777777777777777777777777777777777777777777777777\xff\xc0\x00\x11\x08\x00\x94\x00\xdd\x03\x01\x11\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1c\x00\x01\x00\x02\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x04\x03\x05\x06\x07\x02\x08\xff\xc4\x00I\x10\x00\x01\x04\x01\x01\x05\x04\x05\x07\x06\x0c\x07\x01\x00\x00\x00\x01\x00\x02\x03\x04\x11\x05\x06\x12!1A\x13Qaq"B\x81\x91\xa1\x14\x152R\x82\xb1\xc1\x07Cr\xb2\xd1\xd2\x16#$4Sbs\x92\x93\xa2\xc2\xf03TUc\x94\xe1\xf1%\xff\xc4\x00\x1b\x01\x01\x00\x02\x03\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x06\x01\x04\x05\x02\x07\xff\xc4\x002\x11\x00\x02\x02\x02\x00\x04\x04\x04\x05\x04\x03\x01\x00\x00\x00\x00\x00\x01\x02\x03\x04\x11\x05\x12!1\x13AQq"2a\xb1\x06\

In [ ]:
with open('example5.txt', 'r+') as file:
   content =file.read()
   print(content)
   file.write("New data1")
   print(content)

This is a new line of text.
Add another line
Appending a new line.New dataNew dataNew data
This is a new line of text.
Add another line
Appending a new line.New dataNew dataNew data


In [ ]:
with open('example5.txt','w+') as file:
  file.write("Hello, World!")
  file.seek(0)
  content = file.read()
  print(content)

Hello, World!


In [ ]:
with open('example5.txt','a+') as file:
  file.write("This is a new line.\n")
  file.seek(0)
  content = file.read()
  print(content)


Hello, World!This is a new line.



In [ ]:
with open ('example.txt','r+') as file:
  file.write("This is a new line.\n")
  file.seek(0)
  content = file.read()
  print(content)

This is a new line.



In [ ]:
file.close

In [ ]:
with open("example.txt", "w") as file:
    file.write("Hello, this is a new file.\n")
    file.write("Writing some sample text.")


In [ ]:
with open("example.txt", "r") as file:
    content = file.read()
    print(content)



Hello, this is a new file.
Writing some sample text.


In [ ]:
with open("example.txt", "a") as file:
    file.write("\nThis is an appended line.")


In [ ]:
try:
    with open("example.txt", "x") as file:
        file.write("This file is created exclusively.\n")
except FileExistsError:
    print("File already exists!")



File already exists!


In [ ]:
with open("example_text.txt", "wt") as file:
    file.write("This is text mode writing.\n")


In [ ]:
with open("example_text.txt", "rt") as file:
    content = file.read()
    print(content)


This is text mode writing.



In [ ]:
with open("example.txt", "r+") as file:
    content = file.read()
    file.write("\nThis line is added using r+ mode.")


FileNotFoundError: [Errno 2] No such file or directory: 'example.txt'