In [ ]:
Name = "Aakash Saxena"
Reg="24MCA10008"

In [ ]:
print(Name)
print(Reg)
import numpy as np

# Seucibilityed for reprod

# One-dimensional array
x1 = rng.integers(10, size=6)

# Two-dimensional array
x2 = rng.integers(10, size=(3, 4))

# Three-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))

# Accessing array attributes
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype: ", x3.dtype)


Aakash Saxena
24MCA10008
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:  int64


In [ ]:
print(Name)
print(Reg)
# One-dimensional array indexing
x1 = np.array([9, 4, 0, 3, 8, 6])
print(x1[0])  # Output: 9
print(x1[4])  # Output: 8
print(x1[-1]) # Output: 6

# Multi-dimensional array indexing
x2 = np.array([[3, 1, 3, 7],
               [4, 0, 2, 3],
               [0, 0, 6, 9]])
print(x2[0, 0])  # Output: 3
print(x2[2, 0])  # Output: 0
print(x2[2, -1]) # Output: 9

# Modifying values using indexing
x2[0, 0] = 12
print(x2)

Aakash Saxena
24MCA10008
9
8
6
3
0
9
[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [ ]:
print(Name)
print(Reg)
x1 = np.array([3, 4, 0, 3, 8, 6])
print(x1[:3])    # Output: [3 4 0]
print(x1[3:])    # Output: [3 8 6]
print(x1[1:4])   # Output: [4 0 3]
print(x1[::2])   # Output: [3 0 8]
print(x1[::-1])  # Output: [6 8 3 0 4 3]


Aakash Saxena
24MCA10008
[3 4 0]
[3 8 6]
[4 0 3]
[3 0 8]
[6 8 3 0 4 3]


In [ ]:
print(Name)
print(Reg)
x2 = np.array([[12, 1, 3, 7],
               [4, 0, 2, 3],
               [0, 0, 6, 9]])
print(x2[:2, :3])  # First two rows and three columns
print(x2[:3, ::2]) # Three rows, every second column
print(x2[::-1, ::-1]) # All rows and columns reversed

Aakash Saxena
24MCA10008
[[12  1  3]
 [ 4  0  2]]
[[12  3]
 [ 4  2]
 [ 0  6]]
[[ 9  6  0  0]
 [ 3  2  0  4]
 [ 7  3  1 12]]


In [ ]:
print(Name)
print(Reg)
print(x2[:, 0])  # First column
print(x2[0, :])  # First row
print(x2[0])     # Equivalent to x2[0, :]


Aakash Saxena
24MCA10008
[12  4  0]
[12  1  3  7]
[12  1  3  7]


In [ ]:
print(Name)
print(Reg)
x2_sub = x2[:2, :2]
x2_sub[0, 0] = 99
print(x2_sub)
print(x2)

Aakash Saxena
24MCA10008
[[99  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [ ]:
print(Name)
print(Reg)
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

Aakash Saxena
24MCA10008
[[42  1]
 [ 4  0]]
[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [ ]:
print(Name)
print(Reg)
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

x = np.array([1, 2, 3])
print(x.reshape((1, 3))) # Row vector
print(x.reshape((3, 1))) # Column vector

# Using np.newaxis
print(x[np.newaxis, :]) # Row vector
print(x[:, np.newaxis]) # Column vector


Aakash Saxena
24MCA10008
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [ ]:
print(Name)
print(Reg)
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])

# Concatenate one-dimensional arrays
print(np.concatenate([x, y]))
print(np.concatenate([x, y, z]))

# Concatenate two-dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid, grid]))        # Along first axis
print(np.concatenate([grid, grid], axis=1)) # Along second axis

# Using np.vstack and np.hstack
print(np.vstack([x, grid]))
y = np.array([[99], [99]])
print(np.hstack([grid, y]))


Aakash Saxena
24MCA10008
[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [1 2 3]
 [4 5 6]]
[[ 1  2  3 99]
 [ 4  5  6 99]]


In [ ]:
print(Name)
print(Reg)
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

grid = np.arange(16).reshape((4, 4))

# Vertical split
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

# Horizontal split
left, right = np.hsplit(grid, [2])
print(left)
print(right)


Aakash Saxena
24MCA10008
[1 2 3] [99 99] [3 2 1]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
